# Site settings
title: Cyber-Duck Developer's Blog
email: info@cyber-duck.co.uk
description: "A more technical blog from [Cyber-Duck](http://www.cyber-duck.co.uk/)"
baseurl: ""
url: "http://cyber-duck.github.io/"
username: Cyber-Duck
handle: Cyberduck_uk

# Build settings
markdown: kramdown
permalink: pretty
